services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podcast-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - podcast_network
    
  db:
    image: mysql:8.0
    container_name: podcast_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: podcast_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - podcast_dbdata:/var/lib/mysql
    networks:
      - podcast_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: podcast_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - podcast_network
    depends_on:
      - db

networks:
  podcast_network:
    driver: bridge

volumes:
  podcast_dbdata:
    driver: local